<template>
  <div id="drmm-description">

      <el-row :gutter="20">
        <el-col :span="15">
          <el-card>
            <el-scrollbar style="height:100%;">
              <div class="description-content">
                <h2>1. Introduction</h2>
                <p>The DRMM stands for the Deep Relevance Matching Model, which is a model published in CIKM 2016. The paper title is “A Deep Relevance Matching Model for Ad-hoc Retrieval”. Given a query and a set of documents, DRMM employs a joint deep architecture at the query term level for relevance matching. By using matching histogram mapping, a feed forward matching network, and a term gating network, it effectively capture the three relevance matching factors: exact matching signals, query term importance, and diverse matching requirements.</p>
                <h2>2. Structure</h2>
                <p>The overall structure of the DRMM is shown in the figure. DRMM employs a joint deep architecture at the query term level over the local interactions between query and document terms for relevance matching. It first builds local interactions between each pair of terms from a query and a document based on term embeddings. For each query term, it then transforms the variable-length local interactions into a fixed-length matching histogram. Based on the fixed-length matching histogram, it employs a feed forward matching network to learn hierarchical matching patterns and produce a matching score for each query term. Finally, the overall matching score is generated by aggregating the scores from each single query term with a term gating network computing the aggregation weights.</p>
                <h2>3. Performances</h2>
                <p>The experiments of DRMM is conducted on two TREC collections, Robust04 and ClueWeb09-Cat-B. The details of the two collections are provided in Table 1.</p>
                <table class="result-data60" cellspacing="0">
                  <caption>Table 1: Statistics of the TREC collections used in this study.</caption>
                  <tr>
                    <td class="top-line"></td>
                    <td class="top-line">Robust04</td>
                    <td class="top-line">ClueWeb-09-Cat-B</td>
                  </tr>
                  <tr>
                    <td class="top-line">Vocabulary</td>
                    <td class="top-line">0.6M</td>
                    <td class="top-line">38M</td>
                  </tr>
                  <tr>
                    <td>Document Count</td>
                    <td>0.5M</td>
                    <td>34M</td>
                  </tr>
                  <tr>
                    <td>Collection Length</td>
                    <td>252M</td>
                    <td>26B</td>
                  </tr>
                  <tr>
                    <td class="bottom-line">Query Count</td>
                    <td class="bottom-line">250</td>
                    <td class="bottom-line">150</td>
                  </tr>
                </table>
                <p>The overall results are summarized in Table 2.</p>
                <table class="result-data" cellspacing="0">
                  <caption>Table 2(a): Robust-04 collection</caption>
                  <tr>
                    <td colspan="2" class="top-line"></td>
                    <td colspan="3" class="top-line">Topic titles</td>
                    <td class="top-line" width="15px"></td>
                    <td colspan="3" class="top-line">Topic descriptions</td>
                  </tr>
                  <tr>
                    <td width="20%">Model Type</td>
                    <td>Model Name</td>
                    <td class="top-line">MAP</td>
                    <td class="top-line">nDCG@20</td>
                    <td class="top-line">P@20</td>
                    <td width="15px"></td>
                    <td class="top-line">MAP</td>
                    <td class="top-line">nDCG@20</td>
                    <td class="top-line">P@20</td>
                  </tr>
                  <tr>
                    <td class="top-line" rowspan="2">Traditional Retrieval Baselines</td>
                    <td class="top-line">QL</td>
                    <td class="top-line">0.253</td>
                    <td class="top-line">0.415</td>
                    <td class="top-line">0.369</td>
                    <td width="15px" class="top-line"></td>
                    <td class="top-line">0.246</td>
                    <td class="top-line">0.391</td>
                    <td class="top-line">0.334</td>
                  </tr>
                  <tr>
                    <td>BM25</td>
                    <td>0.253</td>
                    <td>0.415</td>
                    <td>0.369</td>
                    <td></td>
                    <td>0.246</td>
                    <td>0.391</td>
                    <td>0.334</td>
                  </tr>
                  <tr>
                    <td class="top-line" rowspan="3">Representation-Focused Matching Baselines</td>
                    <td class="top-line">DSSM<sub>D</sub></td>
                    <td class="top-line">0.095</td>
                    <td class="top-line">0.201</td>
                    <td class="top-line">0.171</td>
                    <td width="15px" class="top-line"></td>
                    <td class="top-line">0.078</td>
                    <td class="top-line">0.169</td>
                    <td class="top-line">0.145</td>
                  </tr>
                  <tr>
                    <td>CDSSM<sub>D</sub></td>
                    <td>0.067</td>
                    <td>0.146</td>
                    <td>0.125</td>
                    <td></td>
                    <td>0.050</td>
                    <td>0.113</td>
                    <td>0.093</td>
                  </tr>
                  <tr>
                    <td>ARC-I</td>
                    <td>0.041</td>
                    <td>0.066</td>
                    <td>0.065</td>
                    <td></td>
                    <td>0.030</td>
                    <td>0.047</td>
                    <td>0.045</td>
                  </tr>
                  <tr>
                    <td class="top-line" rowspan="4">Interaction-Focused Matching Baselines</td>
                    <td class="top-line">ARC-II</td>
                    <td class="top-line">0.067</td>
                    <td class="top-line">0.147</td>
                    <td class="top-line">0.128</td>
                    <td width="15px" class="top-line"></td>
                    <td class="top-line">0.042</td>
                    <td class="top-line">0.086</td>
                    <td class="top-line">0.074</td>
                  </tr>
                  <tr>
                    <td>MP<sub>IND</sub></td>
                    <td>0.169</td>
                    <td>0.319</td>
                    <td>0.281</td>
                    <td></td>
                    <td>0.067</td>
                    <td>0.142</td>
                    <td>0.118</td>
                  </tr>
                  <tr>
                    <td>MP<sub>COS</sub></td>
                    <td>0.189</td>
                    <td>0.330</td>
                    <td>0.290</td>
                    <td></td>
                    <td>0.094</td>
                    <td>0.190</td>
                    <td>0.162</td>
                  </tr>
                  <tr>
                    <td>MP<sub>DOT</sub></td>
                    <td>0.083</td>
                    <td>0.159</td>
                    <td>0.155</td>
                    <td></td>
                    <td>0.047</td>
                    <td>0.104</td>
                    <td>0.092</td>
                  </tr>
                  <tr>
                    <td class="top-line bottom-line" rowspan="6">Our Approach</td>
                    <td class="top-line">DRMM<sub>CH×TV</sub></td>
                    <td class="top-line">0.253</td>
                    <td class="top-line">0.407</td>
                    <td class="top-line">0.357</td>
                    <td width="15px" class="top-line"></td>
                    <td class="top-line">0.247</td>
                    <td class="top-line">0.404</td>
                    <td class="top-line">0.341</td>
                  </tr>
                  <tr>
                    <td>DRMM<sub>NH×TV</sub></td>
                    <td>0.160</td>
                    <td>0.293</td>
                    <td>0.258</td>
                    <td></td>
                    <td>0.132</td>
                    <td>0.217</td>
                    <td>0.186</td>
                  </tr>
                  <tr>
                    <td>DRMM<sub>LCH×TV</sub></td>
                    <td>0.268</td>
                    <td>0.423</td>
                    <td>0.381</td>
                    <td></td>
                    <td>0.265</td>
                    <td>0.423</td>
                    <td>0.360</td>
                  </tr>
                  <tr>
                    <td>DRMM<sub>CH×IDF</sub></td>
                    <td>0.259</td>
                    <td>0.412</td>
                    <td>0.362</td>
                    <td></td>
                    <td>0.255</td>
                    <td>0.410</td>
                    <td>0.344</td>
                  </tr>
                  <tr>
                    <td>DRMM<sub>NH×IDF</sub></td>
                    <td>0.187</td>
                    <td>0.312</td>
                    <td>0.282</td>
                    <td></td>
                    <td>0.145</td>
                    <td>0.243</td>
                    <td>0.199</td>
                  </tr>
                  <tr>
                    <td class="bottom-line">DRMM<sub>LCH×IDF</sub></td>
                    <td class="bottom-line text-weight">0.279</td>
                    <td class="bottom-line text-weight">0.431</td>
                    <td class="bottom-line text-weight">0.382</td>
                    <td class="bottom-line text-weight"></td>
                    <td class="bottom-line text-weight">0.275</td>
                    <td class="bottom-line text-weight">0.437</td>
                    <td class="bottom-line text-weight">0.371</td>
                  </tr>
                </table>
                <br>
                <table class="result-data" cellspacing="0">
                  <caption>Table 2(b): ClueWeb-09-Cat-B collection</caption>
                  <tr>
                    <td colspan="2" class="top-line"></td>
                    <td colspan="3" class="top-line">Topic titles</td>
                    <td class="top-line" width="15px"></td>
                    <td colspan="3" class="top-line">Topic descriptions</td>
                  </tr>
                  <tr>
                    <td width="20%">Model Type</td>
                    <td>Model Name</td>
                    <td class="top-line">MAP</td>
                    <td class="top-line">nDCG@20</td>
                    <td class="top-line">P@20</td>
                    <td width="15px"></td>
                    <td class="top-line">MAP</td>
                    <td class="top-line">nDCG@20</td>
                    <td class="top-line">P@20</td>
                  </tr>
                  <tr>
                    <td class="top-line" rowspan="2">Traditional Retrieval Baselines</td>
                    <td class="top-line">QL</td>
                    <td class="top-line">0.100</td>
                    <td class="top-line">0.224</td>
                    <td class="top-line">0.328</td>
                    <td width="15px" class="top-line"></td>
                    <td class="top-line">0.075</td>
                    <td class="top-line">0.183</td>
                    <td class="top-line">0.234</td>
                  </tr>
                  <tr>
                    <td>BM25</td>
                    <td>0.101</td>
                    <td>0.225</td>
                    <td>0.326</td>
                    <td></td>
                    <td>0.080</td>
                    <td>0.196</td>
                    <td>0.255</td>
                  </tr>
                  <tr>
                    <td class="top-line" rowspan="5">Representation-Focused Matching Baselines</td>
                    <td class="top-line">DSSM<sub>T</sub></td>
                    <td class="top-line">0.054</td>
                    <td class="top-line">0.132</td>
                    <td class="top-line">0.185</td>
                    <td width="15px" class="top-line"></td>
                    <td class="top-line">0.046</td>
                    <td class="top-line">0.119</td>
                    <td class="top-line">0.143</td>
                  </tr>
                  <tr>
                    <td>CDSSM<sub>D</sub></td>
                    <td>0.039</td>
                    <td>0.099</td>
                    <td>0.131</td>
                    <td></td>
                    <td>0.034</td>
                    <td>0.078</td>
                    <td>0.103</td>
                  </tr>
                  <tr>
                    <td>CDSSM<sub>T</sub></td>
                    <td>0.064</td>
                    <td>0.153</td>
                    <td>0.214</td>
                    <td></td>
                    <td>0.055</td>
                    <td>0.139</td>
                    <td>0.171</td>
                  </tr>
                  <tr>
                    <td>CDSSM<sub>D</sub></td>
                    <td>0.054</td>
                    <td>0.134</td>
                    <td>0.177</td>
                    <td></td>
                    <td>0.049</td>
                    <td>0.125</td>
                    <td>0.160</td>
                  </tr>
                  <tr>
                    <td>ARC-I</td>
                    <td>0.024</td>
                    <td>0.073</td>
                    <td>0.089</td>
                    <td></td>
                    <td>0.017</td>
                    <td>0.036</td>
                    <td>0.051</td>
                  </tr>
                  <tr>
                    <td class="top-line" rowspan="4">Interaction-Focused Matching Baselines</td>
                    <td class="top-line">ARC-II</td>
                    <td class="top-line">0.033</td>
                    <td class="top-line">0.087</td>
                    <td class="top-line">0.123</td>
                    <td width="15px" class="top-line"></td>
                    <td class="top-line">0.024</td>
                    <td class="top-line">0.056</td>
                    <td class="top-line">0.075</td>
                  </tr>
                  <tr>
                    <td>MP<sub>IND</sub></td>
                    <td>0.056</td>
                    <td>0.139</td>
                    <td>0.208</td>
                    <td></td>
                    <td>0.043</td>
                    <td>0.118</td>
                    <td>0.158</td>
                  </tr>
                  <tr>
                    <td>MP<sub>COS</sub></td>
                    <td>0.066</td>
                    <td>0.158</td>
                    <td>0.222</td>
                    <td></td>
                    <td>0.057</td>
                    <td>0.140</td>
                    <td>0.171</td>
                  </tr>
                  <tr>
                    <td>MP<sub>DOT</sub></td>
                    <td>0.044</td>
                    <td>0.109</td>
                    <td>0.158</td>
                    <td></td>
                    <td>0.033</td>
                    <td>0.073</td>
                    <td>0.102</td>
                  </tr>
                  <tr>
                    <td class="top-line bottom-line" rowspan="6">Our Approach</td>
                    <td class="top-line">DRMM<sub>CH×TV</sub></td>
                    <td class="top-line">0.103</td>
                    <td class="top-line">0.245</td>
                    <td class="top-line">0.347</td>
                    <td width="15px" class="top-line"></td>
                    <td class="top-line">0.072</td>
                    <td class="top-line">0.188</td>
                    <td class="top-line">0.253</td>
                  </tr>
                  <tr>
                    <td>DRMM<sub>NH×TV</sub></td>
                    <td>0.065</td>
                    <td>0.151</td>
                    <td>0.213</td>
                    <td></td>
                    <td>0.031</td>
                    <td>0.075</td>
                    <td>0.100</td>
                  </tr>
                  <tr>
                    <td>DRMM<sub>LCH×TV</sub></td>
                    <td>0.111</td>
                    <td>0.250</td>
                    <td>0.361</td>
                    <td></td>
                    <td>0.083</td>
                    <td>0.213</td>
                    <td>0.275</td>
                  </tr>
                  <tr>
                    <td>DRMM<sub>CH×IDF</sub></td>
                    <td>0.104</td>
                    <td>0.252</td>
                    <td>0.354</td>
                    <td></td>
                    <td>0.077</td>
                    <td>0.204</td>
                    <td>0.267</td>
                  </tr>
                  <tr>
                    <td>DRMM<sub>NH×IDF</sub></td>
                    <td>0.066</td>
                    <td>0.151</td>
                    <td>0.216</td>
                    <td></td>
                    <td>0.038</td>
                    <td>0.087</td>
                    <td>0.113</td>
                  </tr>
                  <tr>
                    <td class="bottom-line">DRMM<sub>LCH×IDF</sub></td>
                    <td class="bottom-line text-weight">0.113</td>
                    <td class="bottom-line text-weight">0.258</td>
                    <td class="bottom-line text-weight">0.365</td>
                    <td class="bottom-line text-weight"></td>
                    <td class="bottom-line text-weight">0.087</td>
                    <td class="bottom-line text-weight">0.235</td>
                    <td class="bottom-line text-weight">0.310</td>
                  </tr>
                </table>
                <h2>4. Reference</h2>
                <p>[1] Jiafeng Guo, Yixing Fan. A Deep Relevance Matching Model for Ad-hoc Retrieval[C]. In Proceedings of the Conference on Information and Knowledge Management(CIKM), 2016.</p>
              </div>
            </el-scrollbar>
          </el-card>
        </el-col>
        <el-col :span="9">
          <el-scrollbar style="height:100%;">
            <div class="description-content">
              <el-card>
                <el-scrollbar style="height:100%;">
                  <img src="../../../assets/drmm_structure.png" width="100%">
                </el-scrollbar>
              </el-card>
            </div>
          </el-scrollbar>
        </el-col>
      </el-row>
    </div>
</template>

<script>
  export default {
    name: 'Description',
    mounted: function () {
      // 为了得到卡片的高度，得到窗口的高度
      var winHeight = 0
      if (window.innerHeight) {
        winHeight = window.innerHeight
      } else if ((document.body) && (document.body.clientHeight)) {
        winHeight = document.body.clientHeight
      }
      if (document.documentElement && document.documentElement.clientHeight) {
        winHeight = document.documentElement.clientHeight
      }
      //设置两张卡片的高度
      document.querySelector('.el-card__body').style.height = winHeight - 60 - 20 - 40 - 10 - 70 + 'px'
      document.querySelectorAll('.el-card__body')[1].style.height = winHeight - 60 - 20 - 40 - 10 - 70 + 'px'
      // console.log(document.querySelectorAll('.el-scrollbar__wrap'))
      var scrollbar_list = document.querySelectorAll('.el-scrollbar__wrap')
      console.log(scrollbar_list)
      for (var i = 0; i < 4; i++) {
        scrollbar_list[i].style.overflowX = 'hidden'
      }
      //设置content区域的高度
      var content_block = document.querySelectorAll('.description-content')
      var content_height = winHeight - 60 + 'px'
      for (var i = 0; i < 2; i++) {
        content_block[i].style.height = content_height
      }
    }
  }
</script>

<style scoped>
  .description-content {
    text-align: left;
    font-size: 16px;
    line-height: 24px;
    font-weight: normal;
    font-family: "Lato", "proxima-nova", "Helvetica Neue", Arial, sans-serif;
  }

  .result-data {
    margin:auto;
    width: 95%;
    font-size: 15px;
  }

  .result-data60 {
    margin:auto;
    width: 60%;
    font-size: 15px;
  }

  .top-line {
    border-top: solid 1px black;
  }

  .bottom-line {
    border-bottom: solid 1px black;
  }

  .text-weight {
    font-weight: bold;
  }
</style>
